Implement Ingestion Datahub task
kestra-io/plugin-datahub pull request #1
Opened 2024-08-29 16:21 UTC by iNikitaGricenko

### What changes are being made and why?

- Implemented Ingestion Datahub task ([By request #3309 at kestra-io](https://github.com/kestra-io/kestra/issues/3309))
---

### How the changes have been QAed?

```yaml
- id: execute_ingestion
  type: io.kestra.plugin.datahub.Ingestion
  recipe:
    source:
      type: mysql
      config:
        host_port: 127.0.0.1:3306
        database: dbname
        username: root
        password: "{{ secret('MYSQL_PASSWORD') }}"
    sink:
      type: datahub-rest
      config:
        server: http://datahub-gms:8080
```

---

### Setup Instructions

- Setup datahub docker-compose.quickstart.yml and run. [Datahub Quickstart Guide](https://www.restack.io/docs/datahub-knowledge-datahub-quickstart-guide)
- Start up mysql server locally or in docker (with exposed ip and port)
- Use exposed ip and port for recipe in task

2024-09-02 11:23 UTC, loicmathieu requested changes

2024-09-02 11:23 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/datahub/package-info.java
> +    description = "This sub-group of plugins contains tasks for interacting with Datahub tools using docker.",
```suggestion
    description = "This sub-group of plugins contains tasks for interacting with Datahub.",
```

2024-09-02 11:23 UTC, loicmathieu commented on build.gradle
> +    compileOnly ('com.github.docker-java:docker-java-transport-httpclient5')
You need to import the script library instead:

```
compileOnly group: "io.kestra", name: "script"
```

2024-09-02 11:23 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/datahub/Ingestion.java
> +        @Example(
Please provide full example with a full flow YAML

2024-09-02 11:23 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/datahub/Ingestion.java
Instead of using Docker directly, you should use a taskRunner.
You can take as example the AwsCLI task: https://github.com/kestra-io/plugin-aws/blob/master/src/main/java/io/kestra/plugin/aws/cli/AwsCLI.java

2024-09-04 11:53 UTC, iNikitaGricenko commented
@loicmathieu 
Hello, could you review this implementation?

2024-09-04 18:48 UTC, iNikitaGricenko commented on src/main/java/io/kestra/plugin/datahub/Ingestion.java
> +    private DockerOptions docker;
Have added as not quite sure how to use Task Runner, just to test as datahub-ingestion requires a lot of services, which will have own network, so in test i need to add that network, but sure, will remove that

2024-09-05 07:30 UTC, loicmathieu approved these changes
LGTM

2024-09-05 07:51 UTC, merged